version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-gmpv
    restart: always
    environment:
      MYSQL_DATABASE: bdgmpv
      MYSQL_ROOT_PASSWORD: PassRoot123456 
      MYSQL_USER: user                     
      MYSQL_PASSWORD: pass123456              
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gmpv-network

  app:
    build:
      context: ./GMPV
      dockerfile: Dockerfile
    container_name: springboot-gmpv
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bdgmpv?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user       
      SPRING_DATASOURCE_PASSWORD: pass123456 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - gmpv-network

  frontend:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: react-gmpv
    depends_on:
      - app
    ports:
      - "3000:80"
    networks:
      - gmpv-network

volumes:
  mysql_data:

networks:
  gmpv-network:
